# Enable or disable permission checks for trampling crops.
# Set to true to ignore players that have permission and allow them to trample.
CheckPermissions: true

# Enable or disable prevention of mobs trampling crops.
# Set to false if you want to allow mobs to trample crops as usual.
PreventMobs: true

# Message to display wen a player attempts to trample crops.
# Leave this field empty to disable message notifications.
Message: "&cYou do not have permission to trample on crops."

# Sound to play when a player attempts to trample on crops.
# Use a sound identifier like "BLOCK_NOTE_BLOCK_BASS" for a note sound.
# Leave this field empty to disable sound notifications
Sound: "BLOCK_NOTE_BLOCK_BASS"